import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import test from 'node:test'
import { ACTIVATION_RELEASE, AcademyActivationControllerError, runAcademyProductionActivation, writeControllerReceipt } from './identity-production-activation-controller.mjs'
import { IDENTITY_PRODUCTION_ACTIVATION_CONFIG_NAMES } from './identity-production-activation-preflight.mjs'

const D = 'a'.repeat(64), NOW = new Date('2026-08-29T03:10:00.000Z')
const ids = { deploymentId:'11111111-1111-4111-8111-111111111111', current:'22222222-2222-4222-8222-222222222222', candidate:'33333333-3333-4333-8333-333333333333', activeDeployment:'44444444-4444-4444-8444-444444444444', rollbackDeployment:'55555555-5555-4555-8555-555555555555' }
const configSha256=createHash('sha256').update(`${JSON.stringify(IDENTITY_PRODUCTION_ACTIVATION_CONFIG_NAMES)}\n`).digest('hex')
const readiness = () => ({schema:'identity-control-live-readiness/v1',observedAt:'2026-08-29T03:05:01.000Z',releaseSha:'4acde50e93285e86171fa4713d4d1c390258c16e',runtimeSha256:'f96a89c5c275fb6e80606f54323d26c8e5d98697b12d2bee917046dea3c61e4d',freezeSha256:'aa45a35f3e2d0bf171c6129aef2390a94ab91acf34137bb34685dce4273d5dca',keySetSha256:'d6b557027823437a5fe6378fc26bbd8dffad2d8c58a77c2bcf3583f1350e8e35',artifacts:{accountCenter:{bytes:266240,path:'ac.tar',sha256:'3227c635dbc9235d1861f133615ed2b761351df50f7c3b93c924b088524759f8'},api:{bytes:10127360,path:'api.tar',sha256:'6e1e9e5b140a977d3799c8677649236a25f76d05bad71de288f6d7eeff4f469c'}},activeKeyIds:['academy-prod-2026-08','identity-result-prod-2026-08'],overlapKeyIds:[],registry:{academyClient:{clientId:'academy-web',serviceId:'academy',enabled:true,keyId:'academy-prod-2026-08',reference:'config://client-keys/academy-web/academy-prod-2026-08'},resultSigning:{keyId:'identity-result-prod-2026-08',issuer:'https://accounts.cyberskills.co.th/v1/code/results',revision:1,state:'active'}},production:{mutationStatus:'COMPLETE',mutationCounters:{bootstrapClientsAdopted:1,bootstrapClientsCreated:0,caddyReloads:1,migrationsApplied:1,releasesActivated:1,servicesStarted:1}},evidence:{freezeSha256:'aa45a35f3e2d0bf171c6129aef2390a94ab91acf34137bb34685dce4273d5dca',runtimeSha256:'f96a89c5c275fb6e80606f54323d26c8e5d98697b12d2bee917046dea3c61e4d',keySetSha256:'d6b557027823437a5fe6378fc26bbd8dffad2d8c58a77c2bcf3583f1350e8e35',deploymentModeSha256:D,preflightGoSha256:D,deployReceiptsSha256:D,verifyReceiptsSha256:D,registrySha256:D,healthSha256:D,independentReviewSha256:D},readiness:{deploy:'GO',verify:'GO',registry:'ACTIVE',localReadyStatus:200,publicReadyStatus:403,publicReadyBlocked:true},capturedAt:'2026-08-29T03:05:00.000Z',expiresAt:'2026-08-29T03:20:00.000Z',independentReview:{verdict:'PASS',reviewer:'independent-reviewer',counts:{critical:0,high:0,medium:0,low:0}}})

async function fixture(t) {
  const root=await realpath(await mkdtemp(join(tmpdir(),'academy-controller-'))); t.after(()=>rm(root,{recursive:true,force:true}))
  const identityReadinessPath=join(root,'identity.json'); await writeFile(identityReadinessPath,`${JSON.stringify(readiness())}\n`,{mode:0o600})
  const plan={schema:'academy-production-activation-controller-plan/v1',identityReadinessPath,identityRestore:{status:'MATCH',receiptSha256:D},academy:{sourceRevision:'fa7bca732aefa58ab7fc2c784676a113b873466b',releaseRevision:'fa7bca732aefa58ab7fc2c784676a113b873466b'},workerName:'cyberskills-academy',callbackUri:'https://academy.cyberskills.co.th/auth/callback'}
  const calls=[]
  const ports={
    discoverCurrent:async()=>{calls.push('discover');return{deploymentId:ids.deploymentId,versionId:ids.current}},
    backupRestore:async input=>{calls.push(['backup',input]);return{status:'MATCH',operation:'academy-backup-restore',identityRestoreReceiptSha256:D,receiptSha256:D}},
    applyMigrations:async input=>{calls.push(['migrate',input]);return{status:'PASS',operation:'academy-migrations-0021-0027',ordered:input.ordered,receiptSha256:D}},
    uploadCandidate:async input=>{calls.push(['upload',input]);return{status:'PASS',workerName:'cyberskills-academy',versionId:ids.candidate,sourceRevision:plan.academy.sourceRevision,trafficPercentage:0,configuredNamesSha256:configSha256,receiptSha256:D}},
    activateTraffic:async input=>{calls.push(['activate',input]);return{status:'PASS',previousDeploymentId:ids.deploymentId,previousVersionId:ids.current,deploymentId:ids.activeDeployment,activeVersionId:ids.candidate,trafficPercentage:100,receiptSha256:D}},
    smokeP1P7:async input=>{calls.push(['smoke',input]);return{status:'PASS',deploymentId:ids.activeDeployment,versionId:ids.candidate,configuredNamesSha256:configSha256,checks:['P1','P2','P3','P4','P5','P6','P7'],receiptSha256:D}},
    rollbackTraffic:async input=>{calls.push(['rollback',input]);return{status:'ROLLED_BACK',observedActiveDeploymentId:ids.activeDeployment,observedActiveVersionId:ids.candidate,deploymentId:ids.rollbackDeployment,restoredVersionId:ids.current,receiptSha256:D}},
    checkResidue:async input=>{calls.push(['residue',input]);return{status:'PASS',deploymentId:input.expectedDeploymentId,versionId:input.expectedVersionId,receiptSha256:D}},
  }
  return {root,plan,ports,calls}
}

test('default dry-run validates fresh authority and performs no mutation',async t=>{const f=await fixture(t);const receipt=await runAcademyProductionActivation({plan:f.plan,ports:f.ports,observedAt:NOW});assert.equal(receipt.status,'DRY_RUN');assert.deepEqual(f.calls,['discover']);assert.equal(receipt.steps.filter(x=>x.status==='PLANNED').length,7)})
test('explicit release executes exact ordered activation and binds candidate identity',async t=>{const f=await fixture(t);const receipt=await runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW});assert.equal(receipt.status,'ACTIVATED');assert.deepEqual(f.calls.map(x=>Array.isArray(x)?x[0]:x),['discover','backup','migrate','upload','activate','smoke','residue']);assert.deepEqual(f.calls.find(x=>x[0]==='activate')[1],{candidateVersionId:ids.candidate,expectedCurrentDeploymentId:ids.deploymentId,expectedCurrentVersionId:ids.current,traffic:100});assert.deepEqual(f.calls.find(x=>x[0]==='smoke')[1],{deploymentId:ids.activeDeployment,versionId:ids.candidate,configuredNamesSha256:configSha256});assert.equal(JSON.stringify(receipt).includes('secret'),false)})
test('backup receipt must bind exact Identity restore receipt',async t=>{const f=await fixture(t);f.ports.backupRestore=async()=>({status:'MATCH',operation:'academy-backup-restore',identityRestoreReceiptSha256:'b'.repeat(64),receiptSha256:D});await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_PRE_MUTATION'&&e.receipt.productionMutation===false)})
test('failure after confirmed backup is recovery-required and secret-free',async t=>{const f=await fixture(t);f.ports.applyMigrations=async()=>{throw new Error('secret')};await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e instanceof AcademyActivationControllerError&&e.receipt.status==='FAILED_RECOVERY_REQUIRED'&&e.receipt.productionMutation===true&&e.receipt.mutationLedger.backupRestore==='confirmed'&&!JSON.stringify(e.receipt).includes('secret'))})
test('post-activation smoke failure rolls back with CAS binding and checks residue',async t=>{const f=await fixture(t);f.ports.smokeP1P7=async()=>{throw new Error('private')};await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_TRAFFIC_ROLLED_BACK_RECOVERY_REQUIRED'&&e.receipt.mutationLedger.trafficActivation==='rolled_back');assert.deepEqual(f.calls.find(x=>x[0]==='rollback')[1],{expectedActiveDeploymentId:ids.activeDeployment,expectedActiveVersionId:ids.candidate,priorDeploymentId:ids.deploymentId,targetVersionId:ids.current})})
test('rollback residue failure is uncertain and does not accept rollback receipt',async t=>{const f=await fixture(t);f.ports.smokeP1P7=async()=>{throw new Error()};f.ports.checkResidue=async()=>{throw new Error()};await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_ROLLBACK_UNCERTAIN_RECOVERY_REQUIRED'&&e.receipt.steps.every(x=>x.name!=='rollback'||x.status!=='PASS'))})
test('rollback CAS mismatch is terminal uncertainty',async t=>{const f=await fixture(t);f.ports.smokeP1P7=async()=>{throw new Error()};f.ports.rollbackTraffic=async()=>({status:'ROLLED_BACK',observedActiveDeploymentId:ids.deploymentId,observedActiveVersionId:ids.candidate,deploymentId:ids.rollbackDeployment,restoredVersionId:ids.current,receiptSha256:D});await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_ROLLBACK_UNCERTAIN_RECOVERY_REQUIRED')})
test('unbound activation failure never attempts an unsafe rollback',async t=>{const f=await fixture(t);f.ports.activateTraffic=async()=>{throw new Error()};await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_ROLLBACK_UNCERTAIN_RECOVERY_REQUIRED');assert.equal(f.calls.some(x=>Array.isArray(x)&&x[0]==='rollback'),false)})
test('smoke receipt mismatch triggers bounded rollback',async t=>{const f=await fixture(t);f.ports.smokeP1P7=async()=>({status:'PASS',deploymentId:ids.deploymentId,versionId:ids.candidate,configuredNamesSha256:configSha256,checks:['P1','P2','P3','P4','P5','P6','P7'],receiptSha256:D});await assert.rejects(runAcademyProductionActivation({plan:f.plan,ports:f.ports,release:ACTIVATION_RELEASE,observedAt:NOW}),e=>e.receipt.status==='FAILED_TRAFFIC_ROLLED_BACK_RECOVERY_REQUIRED')})
test('receipt publication is no-clobber and mode 0600',async t=>{const f=await fixture(t),path=join(f.root,'receipt.json');const receipt=await runAcademyProductionActivation({plan:f.plan,ports:f.ports,observedAt:NOW});await writeControllerReceipt(path,receipt);assert.equal(JSON.parse(await readFile(path)).status,'DRY_RUN');await assert.rejects(writeControllerReceipt(path,receipt))})
