#!/usr/bin/env python3
"""สร้างไฟล์ตัวอย่างสำหรับ demo/e2e — ไม่ใช่เนื้อหาจริง

ทำไมต้อง generate แทนที่จะ commit ไฟล์: จะได้ไม่มี binary ที่แก้ไม่ได้อยู่ใน repo
และคนที่ clone ไปสร้างใหม่ได้เสมอ (pattern เดียวกับ make-dummy-lesson-video.sh)

ใช้: python3 scripts/make-dummy-assets.py
"""
import os
import zlib

OUT_DIR = os.path.join("public", "media")
PRIVATE_DIR = os.path.join("private-media", "content-formats-demo", "formats-references")
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(PRIVATE_DIR, exist_ok=True)

# ---------- ไดอะแกรมตัวอย่าง (SVG = ข้อความล้วน ไม่ใช่ binary) ----------
SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 360" width="720" height="360" role="img" aria-label="Diagram placeholder">
  <rect width="720" height="360" fill="#F4F7F6"/>
  <text x="360" y="40" text-anchor="middle" font-family="Georgia, serif" font-size="19" fill="#12211E">Sample diagram (placeholder)</text>

  <rect x="60" y="90" width="170" height="76" rx="12" fill="#FFFFFF" stroke="#00785C" stroke-width="2"/>
  <text x="145" y="126" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="14" fill="#12211E">User space</text>
  <text x="145" y="146" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="11" fill="#5C706A">your programs</text>

  <rect x="275" y="90" width="170" height="76" rx="12" fill="#FFFFFF" stroke="#5B63D3" stroke-width="2"/>
  <text x="360" y="126" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="14" fill="#12211E">Kernel</text>
  <text x="360" y="146" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="11" fill="#5C706A">decides yes or no</text>

  <rect x="490" y="90" width="170" height="76" rx="12" fill="#FFFFFF" stroke="#D6E0DD" stroke-width="2"/>
  <text x="575" y="126" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="14" fill="#12211E">Hardware</text>
  <text x="575" y="146" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="11" fill="#5C706A">disk, network, memory</text>

  <path d="M 230 128 L 268 128" stroke="#00785C" stroke-width="2" marker-end="url(#a)"/>
  <path d="M 445 128 L 483 128" stroke="#5B63D3" stroke-width="2" marker-end="url(#b)"/>
  <defs>
    <marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#00785C"/></marker>
    <marker id="b" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#5B63D3"/></marker>
  </defs>

  <text x="360" y="230" text-anchor="middle" font-family="Helvetica, sans-serif" font-size="12" fill="#5C706A">A program never touches hardware directly. It asks; the kernel answers.</text>
  <text x="360" y="300" text-anchor="middle" font-family="monospace" font-size="11" fill="#6B7A76">placeholder asset - generated by scripts/make-dummy-assets.py</text>
</svg>
"""
svg_path = os.path.join(OUT_DIR, "sample-diagram.svg")
with open(svg_path, "w", encoding="utf-8") as f:
    f.write(SVG)


# ---------- PDF ตัวอย่าง (เขียน PDF ขั้นต่ำเองด้วยมือ ไม่ต้องพึ่ง library) ----------
def make_pdf(path: str, lines: list[str]) -> None:
    content = ["BT", "/F1 18 Tf", "60 760 Td", "16 TL"]
    for i, line in enumerate(lines):
        escaped = line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        if i == 1:
            content.append("/F1 11 Tf")
        content.append(f"({escaped}) Tj")
        content.append("T*")
    content.append("ET")
    stream = "\n".join(content).encode("latin-1")
    compressed = zlib.compress(stream)

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d /Filter /FlateDecode >>\nstream\n" % len(compressed)
        + compressed
        + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"

    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_at,
    )
    with open(path, "wb") as f:
        f.write(bytes(out))


pdf_path = os.path.join(PRIVATE_DIR, "sample-handout.pdf")
make_pdf(
    pdf_path,
    [
        "Linux permissions cheat sheet",
        "",
        "Placeholder handout generated for the Academy UI demo.",
        "Not real course material.",
        "",
        "r = 4    w = 2    x = 1",
        "644  rw-r--r--   documents",
        "755  rwxr-xr-x   programs and directories",
        "600  rw-------   private keys and secrets",
        "777  rwxrwxrwx   never - this is a finding, not a fix",
        "",
        "On a directory: r = list, w = add or delete entries, x = enter",
    ],
)

for path in (svg_path, pdf_path):
    print(f"สร้างแล้ว: {path} ({os.path.getsize(path)} bytes)")
